# Generated by Django 4.0.2 on 2022-05-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_delete_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
    ]
