# Generated by Django 4.0.2 on 2022-05-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.products', verbose_name='продукты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='количество заказа'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Фото'),
        ),
    ]
